name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       PORT: 3333
       HOST: 0.0.0.0
       APP_KEY: testkey
       DRIVE_DISK: local
       NODE_ENV: testing
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Lint
      run: yarn lint
    - name: Run tests
      run: yarn test
